import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Ban,
  Bell,
  Bookmark,
  Bug,
  CheckCircle2,
  Check,
  ChevronRight,
  CircleDot,
  Clipboard,
  Clock,
  Code,
  Cog,
  Eye,
  Filter,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  GitBranch,
  Globe,
  Hammer,
  Heart,
  Info,
  Key,
  Lightbulb,
  Link,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Music,
  Package,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  Pointer,
  Power,
  Puzzle,
  Rocket,
  Save,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  Smile,
  Sparkles,
  Star,
  Tag,
  Terminal,
  Trash2,
  Trophy,
  Wand2,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Emoji string → Lucide icon. Keys are the literal grapheme (including any
// variation selector U+FE0F). Curated for what assistant messages typically
// reach for; unmapped emojis fall through to their normal rendering.
export const EMOJI_TO_ICON: Record<string, LucideIcon> = {
  // status / outcomes
  '✅': CheckCircle2,
  '☑️': CheckCircle2,
  '✔️': Check,
  '✓': Check,
  '❌': X,
  '✖️': X,
  '⛔': Ban,
  '🚫': Ban,
  '⚠️': AlertTriangle,
  'ℹ️': Info,
  '❗': AlertCircle,
  '❕': AlertCircle,
  '❓': AlertCircle,
  '❔': AlertCircle,

  // ideas / actions
  '💡': Lightbulb,
  '✨': Sparkles,
  '🪄': Wand2,
  '🚀': Rocket,
  '🔥': Flame,
  '⚡': Zap,
  '🏆': Trophy,
  '🥇': Award,

  // dev / tooling
  '🐛': Bug,
  '🔧': Wrench,
  '🔨': Hammer,
  '⚙️': Cog,
  '🛠️': Settings,
  '🧪': FlaskConical,
  '🧩': Puzzle,
  '🌿': GitBranch,
  '🌐': Globe,
  '🔗': Link,
  '💻': Terminal,
  '⌨️': Terminal,
  '🖥️': Terminal,
  '👨‍💻': Code,
  '👩‍💻': Code,

  // files / data
  '📁': Folder,
  '📂': Folder,
  '📦': Package,
  '🏷️': Tag,
  '📌': Pin,
  '📎': Clipboard,
  '📋': Clipboard,
  '📝': Pencil,
  '✏️': Pencil,
  '🖊️': Pencil,
  '💾': Save,
  '🗑️': Trash2,

  // people / comms
  '💬': MessageSquare,
  '📣': Megaphone,
  '📢': Megaphone,
  '🔔': Bell,
  '📞': Phone,
  '📧': Mail,
  '✉️': Mail,
  '🙂': Smile,
  '😀': Smile,
  '😃': Smile,
  '👋': Smile,
  '❤️': Heart,
  '💖': Heart,

  // nav / pointer
  '👉': ChevronRight,
  '👆': ArrowUp,
  '👇': ArrowDown,
  '👈': ArrowLeft,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '🔼': ArrowUp,
  '🔽': ArrowDown,
  '🖱️': Pointer,

  // time / state
  '⏰': Clock,
  '⏱️': Clock,
  '🕐': Clock,
  '⏳': Clock,
  '⌛': Clock,
  '▶️': Play,
  '⏸️': Pause,
  '⏹️': Power,
  '🎵': Music,

  // meta
  '🔍': Search,
  '🔎': Search,
  '👀': Eye,
  '🔒': Lock,
  '🔑': Key,
  '🛡️': Shield,
  '🚨': ShieldAlert,
  '⭐': Star,
  '🌟': Star,
  '🚩': Flag,
  '🏁': Flag,
  '📍': MapPin,
  '🔖': Bookmark,
  '🎯': CircleDot,
  '🎉': Sparkles,
  '🎊': Sparkles,
  '🔂': Filter,
};

// Build a regex that matches any mapped emoji. Sort by length-desc so that
// composite sequences (e.g. ⚠️ = U+26A0 U+FE0F) match before their base.
function escapeForRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
const emojiKeys = Object.keys(EMOJI_TO_ICON).sort((a, b) => b.length - a.length);
export const EMOJI_REGEX = new RegExp(`(${emojiKeys.map(escapeForRegex).join('|')})`, 'g');

// Stable key used in HAST element properties; the renderer maps it back to
// the LucideIcon component.
export const ICON_NAMES: Record<string, LucideIcon> = Object.fromEntries(
  Object.entries(EMOJI_TO_ICON).map(([emoji, Icon]) => [emoji, Icon])
);
