import emojiRegex from 'emoji-regex';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Ban,
  Bell,
  BookOpen,
  Bookmark,
  Brain,
  Brush,
  Bug,
  Camera,
  CheckCircle2,
  Check,
  ChevronRight,
  Annoyed,
  Angry,
  Frown,
  Laugh,
  Meh,
  HandHeart,
  HeartCrack,
  HeartHandshake,
  ThumbsDown,
  ThumbsUp,
  Hand,
  CircleDot,
  Clapperboard,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Cog,
  Compass,
  Construction,
  Crown,
  Database,
  Download,
  Eye,
  Filter,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  GitBranch,
  Globe,
  Hammer,
  HardDrive,
  Heart,
  HelpCircle,
  Image,
  Info,
  Key,
  Lightbulb,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircleQuestion,
  MessageSquare,
  Music,
  Package,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  Pointer,
  Power,
  Puzzle,
  RefreshCw,
  Rocket,
  Save,
  Scale,
  Scissors,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  Smile,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Umbrella,
  Upload,
  User,
  Users,
  Wand2,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Emoji string → Lucide icon. Keys are the literal grapheme (including any
// variation selector U+FE0F). Curated for what assistant messages typically
// reach for; unmapped emojis fall through to their normal rendering.
export const EMOJI_TO_ICON: Record<string, LucideIcon> = {
  // status / outcomes
  '✅': CheckCircle2,
  '☑️': CheckCircle2,
  '✔️': Check,
  '✓': Check,
  '❌': X,
  '✖️': X,
  '⛔': Ban,
  '🚫': Ban,
  '⚠️': AlertTriangle,
  'ℹ️': Info,
  '❗': AlertCircle,
  '❕': AlertCircle,

  // ideas / actions
  '💡': Lightbulb,
  '✨': Sparkles,
  '🪄': Wand2,
  '🚀': Rocket,
  '🔥': Flame,
  '⚡': Zap,
  '🏆': Trophy,
  '🥇': Award,

  // dev / tooling
  '🐛': Bug,
  '🔧': Wrench,
  '🔨': Hammer,
  '⚙️': Cog,
  '🛠️': Settings,
  '🧪': FlaskConical,
  '🧩': Puzzle,
  '🌿': GitBranch,
  '🌐': Globe,
  '🔗': Link,
  '💻': Terminal,
  '⌨️': Terminal,
  '🖥️': Terminal,
  '🐚': Terminal, // shell (bash/zsh)
  '🪜': List,
  '✂️': Scissors,
  '🧱': Construction,
  '🏗️': Construction,
  '🪛': Wrench,
  '⚖️': Scale,
  '🧹': Brush,
  '🎨': Palette,
  '🧠': Brain,
  '🪞': RefreshCw,
  '🔄': RefreshCw,
  '🔁': RefreshCw,
  '🔃': RefreshCw,
  '👨‍💻': Code,
  '👩‍💻': Code,

  // files / data
  '📁': Folder,
  '📂': Folder,
  '📦': Package,
  '🏷️': Tag,
  '📌': Pin,
  '📎': Clipboard,
  '📋': Clipboard,
  '📝': Pencil,
  '✏️': Pencil,
  '🖊️': Pencil,
  '💾': Save,
  '💿': Save,
  '💽': HardDrive,
  '🗄️': Database,
  '🗃️': Database,
  '🗑️': Trash2,
  '📚': BookOpen,
  '📖': BookOpen,
  '📕': BookOpen,
  '📗': BookOpen,
  '📘': BookOpen,
  '📙': BookOpen,
  '📔': BookOpen,
  '📒': BookOpen,
  '🖼️': Image,
  '📸': Camera,
  '📷': Camera,
  '🎬': Clapperboard,
  '📊': TrendingUp,
  '📈': TrendingUp,
  '📉': TrendingDown,
  '☁️': Cloud,
  '⬆️📤': Upload,
  '📤': Upload,
  '📥': Download,

  // people / comms
  '💬': MessageSquare,
  '🗨️': MessageSquare,
  '🗯️': MessageSquare,
  '📣': Megaphone,
  '📢': Megaphone,
  '🔔': Bell,
  '📞': Phone,
  '📧': Mail,
  '✉️': Mail,
  '📨': Send,
  '📩': Send,
  // faces
  '🙂': Smile,
  '🙃': Smile,
  '😀': Smile,
  '😃': Smile,
  '😄': Smile,
  '😁': Smile,
  '😆': Laugh,
  '😅': Laugh,
  '🤣': Laugh,
  '😂': Laugh,
  '😊': Smile,
  '☺️': Smile,
  '😉': Smile,
  '😌': Smile,
  '😍': HandHeart,
  '🥰': HandHeart,
  '😘': HandHeart,
  '😗': Smile,
  '😙': Smile,
  '😚': Smile,
  '🤗': HandHeart,
  '🤩': Sparkles,
  '🤔': MessageCircleQuestion,
  '🤨': Meh,
  '😐': Meh,
  '😑': Meh,
  '😶': Meh,
  '🙄': Meh,
  '😏': Meh,
  '😣': Frown,
  '😥': Frown,
  '😮': Frown,
  '😯': Frown,
  '😪': Frown,
  '😫': Frown,
  '🥱': Frown,
  '😴': Frown,
  '😛': Smile,
  '😜': Smile,
  '😝': Smile,
  '🤤': Smile,
  '😒': Annoyed,
  '😓': Frown,
  '😔': Frown,
  '😕': Frown,
  '🙁': Frown,
  '☹️': Frown,
  '😖': Frown,
  '😞': Frown,
  '😟': Frown,
  '😤': Annoyed,
  '😢': Frown,
  '😭': Frown,
  '😦': Frown,
  '😧': Frown,
  '😨': Frown,
  '😩': Frown,
  '🤯': AlertCircle,
  '😬': Meh,
  '😰': Frown,
  '😱': AlertCircle,
  '😳': Frown,
  '🥵': Flame,
  '🥶': Cloud,
  '😡': Angry,
  '😠': Angry,
  '🤬': Angry,
  '😷': Shield,
  '🤒': AlertCircle,
  '🤕': AlertCircle,
  '🤢': Frown,
  '🤮': Frown,
  '🥴': Frown,
  '😵': Frown,
  '🥳': PartyPopper,
  '🥸': User,
  '😎': Smile,
  '🤓': Smile,
  '🧐': Search,
  // hands / body
  '👋': Hand,
  '🤚': Hand,
  '🖐️': Hand,
  '✋': Hand,
  '🖖': Hand,
  '👌': Check,
  '🤌': Hand,
  '🤏': Hand,
  '✌️': Hand,
  '🤞': Hand,
  '🤟': Hand,
  '🤘': Hand,
  '🤙': Hand,
  '👍': ThumbsUp,
  '👎': ThumbsDown,
  '✊': Hand,
  '👊': Hand,
  '🤛': Hand,
  '🤜': Hand,
  '👏': Hand,
  '🙌': Hand,
  '🙏': HandHeart,
  '💪': Activity,
  '❤️': Heart,
  '💖': Heart,
  '👤': User,
  '👥': Users,
  '👑': Crown,

  // nav / pointer
  '👉': ChevronRight,
  '👆': ArrowUp,
  '👇': ArrowDown,
  '👈': ArrowLeft,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '🔼': ArrowUp,
  '🔽': ArrowDown,
  '🖱️': Pointer,

  // time / state
  '⏰': Clock,
  '⏱️': Clock,
  '🕐': Clock,
  '⏳': Clock,
  '⌛': Clock,
  '▶️': Play,
  '⏸️': Pause,
  '⏹️': Power,
  '🎵': Music,

  // meta
  '🔍': Search,
  '🔎': Search,
  '👀': Eye,
  '🔒': Lock,
  '🔓': Lock,
  '🔑': Key,
  '🗝️': Key,
  '🛡️': Shield,
  '🚨': ShieldAlert,
  '⭐': Star,
  '🌟': Star,
  '☀️': Sun,
  '☂️': Umbrella,
  '🚩': Flag,
  '🏁': Flag,
  '📍': MapPin,
  '🗺️': Map,
  '🧭': Compass,
  '🔖': Bookmark,
  '🎯': Target,
  '⚓': CircleDot,
  '🎉': PartyPopper,
  '🎊': PartyPopper,
  '🔂': Filter,
  '❓': HelpCircle,
  '❔': HelpCircle,
};

// Comprehensive emoji matcher (Unicode-spec accurate) — matches *any* emoji,
// not just the ones we have Lucide mappings for. The renderer falls back to
// a Twemoji SVG for unmapped graphemes so coverage is 100%.
export function makeEmojiRegex(): RegExp {
  return emojiRegex();
}

// Convert an emoji string to the Twemoji codepoint filename convention
// (lowercase hex codepoints joined by "-"; the variation selector U+FE0F is
// dropped unless the sequence consists *only* of FE0F-paired pictographs).
export function twemojiCodepoint(emoji: string): string {
  const codepoints: string[] = [];
  for (const ch of emoji) {
    const cp = ch.codePointAt(0);
    if (cp === undefined) continue;
    codepoints.push(cp.toString(16));
  }
  // Twemoji drops FE0F when a sequence has more than one codepoint
  const filtered = codepoints.length > 1 ? codepoints.filter((c) => c !== 'fe0f') : codepoints;
  return filtered.join('-');
}

// Public CDN for Twemoji SVGs. Network-only — there is no bundled fallback,
// so offline users see the system glyph instead of a flat SVG (which is fine).
export function twemojiUrl(emoji: string): string {
  return `https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/svg/${twemojiCodepoint(emoji)}.svg`;
}
