const {
  withInfoPlist,
  withDangerousMod,
  withXcodeProject,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SSL_FILENAME = 'OttoSSL.m';

const SSL_CODE = `\
//
//  OttoSSL.m — Auto-generated by allow-http Expo config plugin.
//  Trusts self-signed certificates for all React Native HTTP requests.
//
//  RCTHTTPRequestHandler already implements URLSession:didReceiveChallenge:,
//  so a category cannot override it. We swizzle the existing method instead.
//

#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTHTTPRequestHandler.h>

// ---- Native module: prevents linker dead-code stripping ----

@interface OttoSSL : NSObject <RCTBridgeModule>
@end

@implementation OttoSSL

RCT_EXPORT_MODULE();

+ (BOOL)requiresMainQueueSetup {
    return NO;
}

@end

// ---- Swizzled replacement for the session-level SSL challenge handler ----

static void OttoSSL_acceptTrust(NSURLAuthenticationChallenge *challenge,
    void (^completionHandler)(NSURLSessionAuthChallengeDisposition,
                              NSURLCredential * _Nullable))
{
    SecTrustRef serverTrust = challenge.protectionSpace.serverTrust;

    // Extract the server certificate and set it as a trusted anchor.
    // This forces SecTrust to evaluate against our explicit anchor list
    // instead of the system root store, bypassing ATS rejection.
    CFIndex certCount = SecTrustGetCertificateCount(serverTrust);
    NSMutableArray *certs = [NSMutableArray arrayWithCapacity:certCount];
    for (CFIndex i = 0; i < certCount; i++) {
        SecCertificateRef cert = SecTrustGetCertificateAtIndex(serverTrust, i);
        if (cert) [certs addObject:(__bridge id)cert];
    }
    if (certs.count > 0) {
        SecTrustSetAnchorCertificates(serverTrust, (__bridge CFArrayRef)certs);
        SecTrustSetAnchorCertificatesOnly(serverTrust, NO);
    }

    // Evaluate trust — we don't care about the result, we accept regardless
    CFErrorRef evalError = NULL;
    bool trusted = SecTrustEvaluateWithError(serverTrust, &evalError);
    NSLog(@"[OttoSSL] trust eval: %s (error: %@)",
          trusted ? "trusted" : "untrusted",
          evalError ? (__bridge NSError *)evalError : nil);
    if (evalError) CFRelease(evalError);

    NSURLCredential *credential =
        [NSURLCredential credentialForTrust:serverTrust];
    completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
}

static void OttoSSL_didReceiveChallenge(id self, SEL _cmd,
    NSURLSession *session,
    NSURLAuthenticationChallenge *challenge,
    void (^completionHandler)(NSURLSessionAuthChallengeDisposition,
                              NSURLCredential * _Nullable))
{
    NSLog(@"[OttoSSL] session challenge: host=%@ method=%@",
          challenge.protectionSpace.host,
          challenge.protectionSpace.authenticationMethod);

    if ([challenge.protectionSpace.authenticationMethod
            isEqualToString:NSURLAuthenticationMethodServerTrust]) {
        OttoSSL_acceptTrust(challenge, completionHandler);
    } else {
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}

// Also handle the per-task variant
static void OttoSSL_task_didReceiveChallenge(id self, SEL _cmd,
    NSURLSession *session,
    NSURLSessionTask *task,
    NSURLAuthenticationChallenge *challenge,
    void (^completionHandler)(NSURLSessionAuthChallengeDisposition,
                              NSURLCredential * _Nullable))
{
    NSLog(@"[OttoSSL] task challenge: host=%@ method=%@",
          challenge.protectionSpace.host,
          challenge.protectionSpace.authenticationMethod);

    if ([challenge.protectionSpace.authenticationMethod
            isEqualToString:NSURLAuthenticationMethodServerTrust]) {
        OttoSSL_acceptTrust(challenge, completionHandler);
    } else {
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}

__attribute__((constructor))
static void OttoSSL_init(void) {
    NSLog(@"[OttoSSL] SSL trust override loaded — swizzling RCTHTTPRequestHandler");

    Class cls = objc_getClass("RCTHTTPRequestHandler");
    if (!cls) {
        NSLog(@"[OttoSSL] ERROR: RCTHTTPRequestHandler class not found");
        return;
    }

    // Swizzle session-level challenge
    SEL sessionSel = @selector(URLSession:didReceiveChallenge:completionHandler:);
    Method sessionMethod = class_getInstanceMethod(cls, sessionSel);
    if (sessionMethod) {
        method_setImplementation(sessionMethod, (IMP)OttoSSL_didReceiveChallenge);
        NSLog(@"[OttoSSL] swizzled URLSession:didReceiveChallenge:completionHandler:");
    } else {
        // Method doesn't exist yet — add it
        const char *types = "v@:@@?";
        class_addMethod(cls, sessionSel, (IMP)OttoSSL_didReceiveChallenge, types);
        NSLog(@"[OttoSSL] added URLSession:didReceiveChallenge:completionHandler:");
    }

    // Swizzle per-task challenge
    SEL taskSel = @selector(URLSession:task:didReceiveChallenge:completionHandler:);
    Method taskMethod = class_getInstanceMethod(cls, taskSel);
    if (taskMethod) {
        method_setImplementation(taskMethod, (IMP)OttoSSL_task_didReceiveChallenge);
        NSLog(@"[OttoSSL] swizzled URLSession:task:didReceiveChallenge:completionHandler:");
    } else {
        const char *types = "v@:@@@?";
        class_addMethod(cls, taskSel, (IMP)OttoSSL_task_didReceiveChallenge, types);
        NSLog(@"[OttoSSL] added URLSession:task:didReceiveChallenge:completionHandler:");
    }
}
`;

function withSSLFile(config) {
  return withDangerousMod(config, [
    'ios',
    (mod) => {
      const iosRoot = mod.modRequest.platformProjectRoot;
      const targetDir = path.join(iosRoot, 'Otto');
      fs.mkdirSync(targetDir, { recursive: true });

      fs.writeFileSync(path.join(targetDir, SSL_FILENAME), SSL_CODE, 'utf-8');

      // Clean up old files
      for (const old of ['RCTHTTPRequestHandler+SSL.m', 'OttoSSLSessionDelegate.m']) {
        const p = path.join(targetDir, old);
        if (fs.existsSync(p)) fs.unlinkSync(p);
      }

      return mod;
    },
  ]);
}

function withSSLXcodeRef(config) {
  return withXcodeProject(config, (mod) => {
    const proj = mod.modResults;
    const targetPath = `Otto/${SSL_FILENAME}`;

    const existing = proj.pbxFileReferenceSection
      ? Object.values(proj.pbxFileReferenceSection()).find(
          (ref) => ref && ref.path === SSL_FILENAME
        )
      : null;

    if (!existing) {
      const groupKey = proj.findPBXGroupKey({ name: 'Otto' });
      proj.addSourceFile(targetPath, null, groupKey);
    }

    // Force linker to keep all Objective-C categories (prevents dead-code stripping)
    const configs = proj.pbxXCBuildConfigurationSection();
    for (const key in configs) {
      const cfg = configs[key];
      if (cfg && cfg.buildSettings) {
        const flags = cfg.buildSettings.OTHER_LDFLAGS;
        if (Array.isArray(flags)) {
          if (!flags.includes('"-ObjC"')) {
            flags.push('"-ObjC"');
          }
        } else if (typeof flags === 'string') {
          if (!flags.includes('-ObjC')) {
            cfg.buildSettings.OTHER_LDFLAGS = [flags, '"-ObjC"'];
          }
        } else {
          cfg.buildSettings.OTHER_LDFLAGS = ['"$(inherited)"', '"-ObjC"'];
        }
      }
    }

    return mod;
  });
}

module.exports = function allowHttp(config) {
  config = withInfoPlist(config, (mod) => {
    mod.modResults.NSAppTransportSecurity = {
      NSAllowsArbitraryLoads: true,
      NSAllowsLocalNetworking: true,
    };
    mod.modResults.NSLocalNetworkUsageDescription =
      'Otto needs local network access to communicate with your desktop over Tailscale.';
    mod.modResults.NSBonjourServices = ['_otto._tcp'];
    return mod;
  });

  config = withSSLFile(config);
  config = withSSLXcodeRef(config);

  return config;
};
