import { promises as fsp } from 'node:fs';
import path from 'node:path';
import type { FactRepo } from '../db/fact-repo';

const FILENAME = 'knowledge.md';
const HEADER =
  '<!-- auto-generated by Otto; edits will be overwritten on next reflection -->\n' +
  '# Otto pinned facts\n\nDurable facts Otto currently keeps in its working set. Edits here are NOT read back; the source of truth is the SQLite store.\n\n';

export function renderPinnedAsMarkdown(repo: FactRepo): string {
  const pinned = repo.listPinned();
  if (pinned.length === 0) return '';
  return pinned.map((f) => `- ${f.body}`).join('\n');
}

export async function regenerateKnowledgeFile(configDir: string, repo: FactRepo): Promise<void> {
  const body = renderPinnedAsMarkdown(repo);
  const text = body.length === 0 ? `${HEADER}(none yet)\n` : `${HEADER}${body}\n`;
  await fsp.writeFile(path.join(configDir, FILENAME), text, 'utf8');
}
